name: Hillel Arithmetics Lib sonarQube pipeline

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish package
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=Hillel-Arithmetics-Lib -Dsonar.projectName='Hillel Arithmetics Lib' -Dsonar.host.url=${{ secrets.SONAR_HOST }} -Dsonar.token=${{ secrets.SONAR_TOKEN }}